zstyle ':prezto:module:prompt' pwd-length 'short'
zstyle ':prezto:module:editor' key-bindings 'vi'
zstyle ':prezto:module:editor' dot-expansion 'yes'
zstyle ':prezto:module:editor' ps-context 'yes'
#zstyle ':prezto:module:editor:info:keymap:primary' format '>>>'
#zstyle ':prezto:module:editor:info:keymap:primary:insert' format 'I'
#zstyle ':prezto:module:editor:info:keymap:primary:overwrite' format 'I'
#zstyle ':prezto:module:editor:info:keymap:alternate' format 'I'
#zstyle ':prezto:module:editor:info:completing' format '...'
zstyle ':prezto:module:git:log:context' format 'brief'
zstyle ':prezto:module:git:log:oneline' format '%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'
zstyle ':prezto:module:git:status:ignore' submodules 'all'
zstyle ':prezto:*:*' case-sensitive 'no'
zstyle ':prezto:*:*' color 'yes'
#zstyle ':prezto:module:python:virtualenv' auto-switch 'yes'
zstyle ':prezto:module:completion:*:hosts' etc-host-ignores '0.0.0.0' '127.0.0.1'

:<<'COMMENT:TODO'
zstyle ':prezto:module:python' skip-virtualenvwrapper-init 'on'
COMMENT:TODO
